// GENERATED from the Crustdata OpenAPI 2025-11-01 spec by scripts/gen-filter-fields.mjs.
// Do not edit by hand; run `npm run gen:fields` and commit the result.
//
// Note the dialect: the range operators are `=>` and `=<`, reversed from the
// near-universal `>=` and `<=`. A picker is how the node makes that unmissable.

import type { INodePropertyOptions } from 'n8n-workflow';

export const PERSON_FILTER_FIELDS: string[] = [
	"crustdata_person_id",
	"basic_profile.name",
	"basic_profile.headline",
	"basic_profile.summary",
	"basic_profile.languages",
	"basic_profile.last_updated",
	"basic_profile.location",
	"basic_profile.location.full_location",
	"basic_profile.location.city",
	"basic_profile.location.state",
	"basic_profile.location.country",
	"basic_profile.location.continent",
	"basic_profile.normalized_title.matched_title",
	"basic_profile.normalized_title.department",
	"basic_profile.normalized_title.sub_department",
	"professional_network.connections",
	"professional_network.followers",
	"professional_network.open_to_cards",
	"professional_network.location",
	"professional_network.location.raw",
	"skills.professional_network_skills",
	"experience.employment_details.company_name",
	"experience.employment_details.company_id",
	"experience.employment_details.professional_network_id",
	"experience.employment_details.title",
	"experience.employment_details.description",
	"experience.employment_details.location",
	"experience.employment_details.start_date",
	"experience.employment_details.end_date",
	"experience.employment_details.seniority_level",
	"experience.employment_details.function_category",
	"experience.employment_details.company_website_domain",
	"experience.employment_details.company_headcount_latest",
	"experience.employment_details.company_headcount_range",
	"experience.employment_details.company_industries",
	"experience.employment_details.company_professional_network_industry",
	"experience.employment_details.company_type",
	"experience.employment_details.company_status",
	"experience.employment_details.company_headquarters_country",
	"experience.employment_details.company_hq_location",
	"experience.employment_details.years_at_company_raw",
	"experience.employment_details.current.name",
	"experience.employment_details.current.company_name",
	"experience.employment_details.current.title",
	"experience.employment_details.current.description",
	"experience.employment_details.current.company_id",
	"experience.employment_details.current.professional_network_id",
	"experience.employment_details.current.is_default",
	"experience.employment_details.current.position_id",
	"experience.employment_details.current.seniority_level",
	"experience.employment_details.current.start_date",
	"experience.employment_details.current.company_website_domain",
	"experience.employment_details.current.company_professional_network_industry",
	"experience.employment_details.current.company_linkedin_profile_url",
	"experience.employment_details.current.company_headcount_range",
	"experience.employment_details.current.company_headcount_latest",
	"experience.employment_details.current.company_industries",
	"experience.employment_details.current.company_type",
	"experience.employment_details.current.company_status",
	"experience.employment_details.current.company_headquarters_country",
	"experience.employment_details.current.company_hq_location",
	"experience.employment_details.current.function_category",
	"experience.employment_details.current.years_at_company_raw",
	"experience.employment_details.past.name",
	"experience.employment_details.past.company_name",
	"experience.employment_details.past.title",
	"experience.employment_details.past.description",
	"experience.employment_details.past.company_id",
	"experience.employment_details.past.professional_network_id",
	"experience.employment_details.past.is_default",
	"experience.employment_details.past.position_id",
	"experience.employment_details.past.seniority_level",
	"experience.employment_details.past.start_date",
	"experience.employment_details.past.company_website_domain",
	"experience.employment_details.past.company_professional_network_industry",
	"experience.employment_details.past.company_linkedin_profile_url",
	"experience.employment_details.past.company_headcount_range",
	"experience.employment_details.past.company_headcount_latest",
	"experience.employment_details.past.company_industries",
	"experience.employment_details.past.company_type",
	"experience.employment_details.past.company_status",
	"experience.employment_details.past.company_headquarters_country",
	"experience.employment_details.past.company_hq_location",
	"experience.employment_details.past.function_category",
	"experience.employment_details.past.years_at_company_raw",
	"education.schools.school",
	"education.schools.degree",
	"education.schools.field_of_study",
	"education.schools.location",
	"education.schools.location.city",
	"education.schools.location.state",
	"education.schools.location.country",
	"education.schools.location.continent",
	"education.schools.location.full_location",
	"education.schools.location.raw",
	"certifications.name",
	"certifications.issue_date",
	"certifications.expiration_date",
	"certifications.credential_url",
	"certifications.issuing_organization",
	"certifications.credential_id",
	"honors.title",
	"social_handles.twitter_handle",
	"basic_profile.first_name",
	"basic_profile.last_name",
	"recently_changed_jobs",
	"years_of_experience_raw",
	"experience.employment_details.current.business_email_verified",
	"experience.employment_details.past.business_email_verified",
	"experience.employment_details.business_email_verified",
	"metadata.last_scraped_source",
	"metadata.updated_at",
	"professional_network.location.city",
	"professional_network.location.state",
	"professional_network.location.country",
	"professional_network.location.continent",
	"professional_network.metadata.last_scraped_source",
	"experience.employment_details.employment_type",
	"experience.employment_details.is_default",
	"experience.employment_details.company_website",
	"experience.employment_details.current.company_professional_network_profile_url",
	"experience.employment_details.current.employment_type",
	"experience.employment_details.past.company_professional_network_profile_url",
	"experience.employment_details.past.employment_type",
	"years_of_experience",
	"dev_platform_profiles.name",
	"dev_platform_profiles.bio",
	"dev_platform_profiles.location",
	"dev_platform_profiles.location.raw",
	"dev_platform_profiles.website_url",
	"dev_platform_profiles.company_text",
	"dev_platform_profiles.is_hireable",
	"dev_platform_profiles.followers",
	"dev_platform_profiles.following",
	"dev_platform_profiles.public_repo_count",
	"dev_platform_profiles.metadata.created_at",
	"dev_platform_profiles.total_repos",
	"dev_platform_profiles.total_stars",
	"dev_platform_profiles.max_stars",
	"dev_platform_profiles.median_stars",
	"dev_platform_profiles.all_languages",
	"dev_platform_profiles.all_topics",
	"dev_platform_profiles.repos.full_name",
	"dev_platform_profiles.repos.owner",
	"dev_platform_profiles.repos.is_fork",
	"dev_platform_profiles.repos.description",
	"dev_platform_profiles.repos.primary_language",
	"dev_platform_profiles.repos.topics",
	"dev_platform_profiles.repos.license_key",
	"dev_platform_profiles.repos.archived",
	"dev_platform_profiles.repos.disabled",
	"dev_platform_profiles.repos.is_template",
	"dev_platform_profiles.repos.has_issues",
	"dev_platform_profiles.repos.has_projects",
	"dev_platform_profiles.repos.has_wiki",
	"dev_platform_profiles.repos.stars",
	"dev_platform_profiles.repos.forks_count",
	"dev_platform_profiles.repos.open_issues_count",
	"dev_platform_profiles.repos.size",
	"dev_platform_profiles.repos.github_created_at",
	"dev_platform_profiles.repos.github_updated_at",
	"dev_platform_profiles.repos.github_pushed_at",
	"assessment.authenticity.tier",
	"assessment.authenticity.verdict",
];

export const COMPANY_FILTER_FIELDS: string[] = [
	"crustdata_company_id",
	"updated_at",
	"indexed_at",
	"metadata.growth_calculation_date",
	"basic_info.company_id",
	"basic_info.name",
	"basic_info.primary_domain",
	"basic_info.website",
	"basic_info.professional_network_url",
	"basic_info.professional_network_id",
	"basic_info.company_type",
	"basic_info.status",
	"basic_info.year_founded",
	"basic_info.employee_count_range",
	"basic_info.markets",
	"basic_info.industries",
	"revenue.estimated.lower_bound_usd",
	"revenue.estimated.upper_bound_usd",
	"revenue.acquisition_status",
	"funding.total_investment_usd",
	"funding.last_round_amount_usd",
	"funding.last_fundraise_date",
	"funding.last_round_type",
	"funding.investors",
	"funding.tracxn_investors",
	"headcount.total",
	"headcount.growth_percent.1m",
	"headcount.growth_percent.3m",
	"headcount.growth_percent.6m",
	"headcount.growth_percent.12m",
	"headcount.growth_absolute.1m",
	"headcount.growth_absolute.3m",
	"headcount.growth_absolute.6m",
	"headcount.growth_absolute.12m",
	"roles.distribution",
	"roles.distribution.accounting",
	"roles.distribution.administrative",
	"roles.distribution.arts_and_design",
	"roles.distribution.business_development",
	"roles.distribution.community_and_social_services",
	"roles.distribution.consulting",
	"roles.distribution.customer_success_and_support",
	"roles.distribution.education",
	"roles.distribution.engineering",
	"roles.distribution.entrepreneurship",
	"roles.distribution.finance",
	"roles.distribution.healthcare_services",
	"roles.distribution.human_resources",
	"roles.distribution.information_technology",
	"roles.distribution.legal",
	"roles.distribution.marketing",
	"roles.distribution.media_and_communication",
	"roles.distribution.military_and_protective_services",
	"roles.distribution.operations",
	"roles.distribution.product_management",
	"roles.distribution.program_and_project_management",
	"roles.distribution.purchasing",
	"roles.distribution.quality_assurance",
	"roles.distribution.real_estate",
	"roles.distribution.research",
	"roles.distribution.sales",
	"roles.distribution.support",
	"roles.growth_6m",
	"roles.growth_yoy",
	"roles.distribution_percent",
	"locations.country",
	"locations.headquarters",
	"locations.street_address",
	"locations.all_office_addresses",
	"headcount.largest_headcount_country",
	"taxonomy.professional_network_industry",
	"taxonomy.professional_network_specialities",
	"taxonomy.categories",
	"followers.count",
	"followers.mom_percent",
	"followers.qoq_percent",
	"followers.six_months_growth_percent",
	"followers.yoy_percent",
	"competitors.company_ids",
	"competitors.websites",
	"revenue.public_markets.fiscal_year_end",
	"revenue.public_markets.ipo_date",
	"revenue.public_markets.stock_symbols",
	"social_profiles.crunchbase.url",
	"social_profiles.crunchbase.uuid",
	"social_profiles.twitter_url",
	"social_profiles.professional_network",
	"technographics.total_technologies",
	"technographics.technologies.name",
	"technographics.technologies.category",
	"technographics.technologies.super_category",
	"technographics.top_technologies",
];

export const JOB_FILTER_FIELDS: string[] = [
	"job_details.title",
	"job_details.category",
	"job_details.workplace_type",
	"job_details.reposted_job",
	"job_details.url",
	"company.basic_info.company_id",
	"company.basic_info.name",
	"company.basic_info.primary_domain",
	"company.basic_info.professional_network_id",
	"company.basic_info.industries",
	"company.headcount.total",
	"company.headcount.range",
	"company.followers.count",
	"company.revenue.estimated.lower_bound_usd",
	"location.raw",
	"location.country",
	"location.state",
	"location.district",
	"location.city",
	"geo_distance",
	"geo_exclude",
	"location",
	"technographics.technologies.name",
	"technographics.technologies.category",
	"technographics.technologies.super_category",
	"job_details.source",
	"professional_network",
	"content.description",
	"crustdata_job_id",
	"metadata.date_added",
	"metadata.date_updated",
];

export const SOCIALPOST_FILTER_FIELDS: string[] = [
	"share_urn",
	"backend_urn",
	"entity_urn",
	"parent_post_urn",
	"share_url",
	"text",
	"hashtags",
	"post_type",
	"date_posted",
	"is_edited",
	"has_video",
	"actor.actor_type",
	"actor.crustdata_entity_id",
	"actor.linkedin_id",
	"actor.professional_network_urn",
	"actor.professional_network_url",
	"actor.name",
	"actor.headline",
	"actor.title",
	"actor.company_name",
	"actor.industry",
	"actor.location.raw",
	"actor.location.city",
	"actor.location.state",
	"actor.location.country",
	"actor.location.continent",
	"reposter.actor_type",
	"reposter.linkedin_id",
	"reposter.professional_network_urn",
	"reposter.professional_network_url",
	"reposter.name",
	"reposter.headline",
	"engagement.total_reactions",
	"engagement.total_comments",
	"engagement.num_shares",
	"reactors.actor_type",
	"reactors.crustdata_entity_id",
	"reactors.linkedin_id",
	"reactors.name",
	"reactors.headline",
	"reactors.location",
	"reactors.title",
	"reactors.company",
	"reactors.industry",
	"comments.created_at",
	"comments.actor_type",
	"comments.crustdata_entity_id",
	"comments.linkedin_id",
	"comments.name",
	"comments.headline",
	"comments.location",
	"comments.title",
	"comments.company",
	"comments.industry",
	"comments.professional_network_url",
	"mentions.person_id",
	"mentions.company_id",
	"mentions.person_url",
	"mentions.company_url",
	"document.title",
	"document.page_count",
	"article.title",
	"poll.question",
	"poll.closed",
	"image",
	"document",
	"article",
];

export const PERSON_AUTOCOMPLETE_FIELDS: string[] = [
	"basic_profile.name",
	"basic_profile.first_name",
	"basic_profile.last_name",
	"basic_profile.headline",
	"basic_profile.languages",
	"basic_profile.location",
	"basic_profile.location.raw",
	"basic_profile.location.full_location",
	"basic_profile.location.city",
	"basic_profile.location.state",
	"basic_profile.location.country",
	"basic_profile.location.continent",
	"professional_network.location",
	"professional_network.location.raw",
	"professional_network.location.city",
	"professional_network.location.state",
	"professional_network.location.country",
	"professional_network.location.continent",
	"professional_network.open_to_cards",
	"skills.professional_network_skills",
	"experience.employment_details.current.name",
	"experience.employment_details.current.title",
	"experience.employment_details.current.seniority_level",
	"experience.employment_details.current.function_category",
	"experience.employment_details.current.company_industries",
	"experience.employment_details.current.company_type",
	"experience.employment_details.current.company_hq_location",
	"experience.employment_details.current.company_website_domain",
	"experience.employment_details.current.employment_type",
	"experience.employment_details.past.name",
	"experience.employment_details.past.title",
	"experience.employment_details.past.seniority_level",
	"experience.employment_details.past.function_category",
	"experience.employment_details.past.company_type",
	"experience.employment_details.past.company_hq_location",
	"experience.employment_details.past.company_website_domain",
	"experience.employment_details.past.employment_type",
	"experience.employment_details.employment_type",
	"education.schools.school",
	"education.schools.degree",
	"education.schools.field_of_study",
	"certifications.name",
	"certifications.issuing_organization",
	"honors.title",
	"open_to_cards",
	"employment_type",
];

export const COMPANY_AUTOCOMPLETE_FIELDS: string[] = [
	"basic_info.name",
	"basic_info.primary_domain",
	"basic_info.website",
	"basic_info.professional_network_url",
	"basic_info.professional_network_id",
	"basic_info.company_type",
	"basic_info.year_founded",
	"basic_info.employee_count_range",
	"basic_info.markets",
	"basic_info.industries",
	"revenue.estimated.lower_bound_usd",
	"revenue.estimated.upper_bound_usd",
	"revenue.acquisition_status",
	"funding.total_investment_usd",
	"funding.last_round_type",
	"funding.last_fundraise_date",
	"funding.investors",
	"funding.tracxn_investors",
	"headcount.latest_count",
	"headcount.largest_headcount_country",
	"locations.country",
	"taxonomy.professional_network_industry",
	"taxonomy.professional_network_specialities",
	"taxonomy.categories",
	"technographics.technologies.name",
	"technographics.technologies.category",
	"technographics.top_technologies",
	"followers.latest_count",
	"social_profiles.crunchbase.url",
	"social_profiles.twitter_url",
	"revenue.public_markets.stock_symbols",
];

export const JOB_AUTOCOMPLETE_FIELDS: string[] = [
	"title",
	"category",
	"company.name",
	"company.industries",
	"location.country",
	"location.city",
	"location.state",
	"city",
	"company.basic_info.industries",
	"company.basic_info.name",
	"company.basic_info.primary_domain",
	"company.funding.investors",
	"company.funding.last_round_type",
	"company.headcount.largest_country",
	"company.headcount.range",
	"company.locations.city",
	"company.locations.country",
	"company.locations.state",
	"company.revenue.acquisition_status",
	"company.revenue.public_markets.fiscal_year_end",
	"company.revenue.public_markets.stock_symbols",
	"continent",
	"country",
	"country_code",
	"district",
	"fiscal_year_end",
	"job_category",
	"job_details.category",
	"job_details.title",
	"job_details.workplace_type",
	"job_title",
	"location",
	"location.district",
	"location.raw",
	"locations.city",
	"locations.country",
	"locations.district",
	"locations.location",
	"locations.state",
	"state",
	"technographics.technologies.category",
	"technographics.technologies.name",
	"technology",
	"technology_category",
	"workplace_type",
];

export const PERSON_SORTABLE_FIELDS: string[] = [
	"crustdata_person_id",
	"basic_profile.name",
	"basic_profile.location",
	"basic_profile.location.full_location",
	"basic_profile.location.city",
	"basic_profile.location.state",
	"basic_profile.location.country",
	"professional_network.connections",
	"professional_network.followers",
	"experience.employment_details.start_date",
	"experience.employment_details.company_id",
	"metadata.updated_at",
	"dev_platform_profiles.followers",
	"dev_platform_profiles.following",
	"dev_platform_profiles.metadata.created_at",
	"dev_platform_profiles.public_repo_count",
	"dev_platform_profiles.total_repos",
	"dev_platform_profiles.total_stars",
	"dev_platform_profiles.max_stars",
	"dev_platform_profiles.median_stars",
	"assessment.authenticity.tier",
];

export const COMPANY_SORTABLE_FIELDS: string[] = [
	"crustdata_company_id",
	"updated_at",
	"indexed_at",
	"metadata.growth_calculation_date",
	"basic_info.company_id",
	"basic_info.name",
	"basic_info.primary_domain",
	"basic_info.year_founded",
	"basic_info.employee_count_range",
	"revenue.estimated.lower_bound_usd",
	"revenue.estimated.upper_bound_usd",
	"revenue.public_markets.ipo_date",
	"funding.total_investment_usd",
	"funding.last_round_amount_usd",
	"funding.last_fundraise_date",
	"headcount.total",
	"headcount.largest_headcount_country",
	"followers.count",
	"locations.country",
	"technographics.total_technologies",
];

export const JOB_SORTABLE_FIELDS: string[] = [
	"metadata.date_added",
	"metadata.date_updated",
	"company.headcount.total",
	"company.followers.count",
];

export const SOCIALPOST_SORTABLE_FIELDS: string[] = [
	"post_type",
	"actor.actor_type",
	"engagement.total_reactions",
	"engagement.total_comments",
	"engagement.num_shares",
	"is_edited",
	"has_video",
	"poll.closed",
	"poll.multi_select",
];

export const PERSON_RETURN_PATHS: string[] = [
	"basic_profile",
	"basic_profile.current_title",
	"basic_profile.headline",
	"basic_profile.location",
	"basic_profile.location.city",
	"basic_profile.location.continent",
	"basic_profile.location.country",
	"basic_profile.location.raw",
	"basic_profile.location.state",
	"basic_profile.name",
	"basic_profile.normalized_title",
	"basic_profile.normalized_title.confident",
	"basic_profile.normalized_title.department",
	"basic_profile.normalized_title.matched_title",
	"basic_profile.normalized_title.similarity",
	"basic_profile.normalized_title.sub_department",
	"basic_profile.professional_network_name",
	"basic_profile.profile_picture_permalink",
	"contact",
	"contact.has_business_email",
	"crustdata_person_id",
	"education",
	"education.schools",
	"education.schools.activities_and_societies",
	"education.schools.degree",
	"education.schools.description",
	"education.schools.end_year",
	"education.schools.field_of_study",
	"education.schools.institute_logo_permalink",
	"education.schools.institute_logo_url",
	"education.schools.location",
	"education.schools.location.city",
	"education.schools.location.continent",
	"education.schools.location.country",
	"education.schools.location.raw",
	"education.schools.location.state",
	"education.schools.professional_network_id",
	"education.schools.school",
	"education.schools.start_year",
	"experience",
	"experience.employment_details",
	"experience.employment_details.current",
	"experience.employment_details.current.business_email_verified",
	"experience.employment_details.current.company_headcount_latest",
	"experience.employment_details.current.company_headcount_range",
	"experience.employment_details.current.company_headquarters_country",
	"experience.employment_details.current.company_hq_location",
	"experience.employment_details.current.company_hq_location_address_components",
	"experience.employment_details.current.company_industries",
	"experience.employment_details.current.company_professional_network_industry",
	"experience.employment_details.current.company_professional_network_profile_url",
	"experience.employment_details.current.company_profile_picture_permalink",
	"experience.employment_details.current.company_status",
	"experience.employment_details.current.company_type",
	"experience.employment_details.current.company_website",
	"experience.employment_details.current.company_website_domain",
	"experience.employment_details.current.crustdata_company_id",
	"experience.employment_details.current.description",
	"experience.employment_details.current.employment_type",
	"experience.employment_details.current.end_date",
	"experience.employment_details.current.function_category",
	"experience.employment_details.current.is_default",
	"experience.employment_details.current.location",
	"experience.employment_details.current.location.raw",
	"experience.employment_details.current.name",
	"experience.employment_details.current.position_id",
	"experience.employment_details.current.professional_network_id",
	"experience.employment_details.current.seniority_level",
	"experience.employment_details.current.start_date",
	"experience.employment_details.current.title",
	"experience.employment_details.current.years_at_company",
	"experience.employment_details.current.years_at_company_raw",
	"experience.employment_details.past",
	"experience.employment_details.past.business_email_verified",
	"experience.employment_details.past.company_headcount_latest",
	"experience.employment_details.past.company_headcount_range",
	"experience.employment_details.past.company_headquarters_country",
	"experience.employment_details.past.company_hq_location",
	"experience.employment_details.past.company_hq_location_address_components",
	"experience.employment_details.past.company_industries",
	"experience.employment_details.past.company_professional_network_industry",
	"experience.employment_details.past.company_professional_network_profile_url",
	"experience.employment_details.past.company_profile_picture_permalink",
	"experience.employment_details.past.company_status",
	"experience.employment_details.past.company_type",
	"experience.employment_details.past.company_website",
	"experience.employment_details.past.company_website_domain",
	"experience.employment_details.past.crustdata_company_id",
	"experience.employment_details.past.description",
	"experience.employment_details.past.employment_type",
	"experience.employment_details.past.end_date",
	"experience.employment_details.past.function_category",
	"experience.employment_details.past.is_default",
	"experience.employment_details.past.location",
	"experience.employment_details.past.location.raw",
	"experience.employment_details.past.name",
	"experience.employment_details.past.position_id",
	"experience.employment_details.past.professional_network_id",
	"experience.employment_details.past.seniority_level",
	"experience.employment_details.past.start_date",
	"experience.employment_details.past.title",
	"experience.employment_details.past.years_at_company",
	"experience.employment_details.past.years_at_company_raw",
	"metadata",
	"metadata.updated_at",
	"social_handles",
	"social_handles.dev_platform_identifier",
	"social_handles.dev_platform_identifier.profile_url",
	"social_handles.professional_network_identifier",
	"social_handles.professional_network_identifier.profile_url",
	"social_handles.twitter_identifier",
	"social_handles.twitter_identifier.slug",
];

export const COMPANY_RETURN_PATHS: string[] = [
	"basic_info",
	"basic_info.all_domains",
	"basic_info.company_type",
	"basic_info.crustdata_company_id",
	"basic_info.description",
	"basic_info.employee_count_range",
	"basic_info.industries",
	"basic_info.logo_permalink",
	"basic_info.markets",
	"basic_info.name",
	"basic_info.primary_domain",
	"basic_info.professional_network_id",
	"basic_info.professional_network_url",
	"basic_info.profile_name",
	"basic_info.status",
	"basic_info.website",
	"basic_info.year_founded",
	"crustdata_company_id",
	"followers",
	"followers.count",
	"followers.mom_percent",
	"followers.qoq_percent",
	"followers.six_months_growth_percent",
	"followers.yoy_percent",
	"funding",
	"funding.investors",
	"funding.last_fundraise_date",
	"funding.last_round_amount_usd",
	"funding.last_round_type",
	"funding.total_investment_usd",
	"headcount",
	"headcount.growth_absolute",
	"headcount.growth_percent",
	"headcount.largest_headcount_country",
	"headcount.total",
	"hiring",
	"hiring.by_function_6m_pct",
	"hiring.by_function_qoq_pct",
	"hiring.openings_count",
	"hiring.openings_growth_percent",
	"indexed_at",
	"locations",
	"locations.all_office_addresses",
	"locations.country",
	"locations.headquarters",
	"locations.state",
	"locations.street_address",
	"metadata",
	"metadata.growth_calculation_date",
	"revenue",
	"revenue.acquisition_status",
	"revenue.estimated",
	"revenue.estimated.lower_bound_usd",
	"revenue.estimated.upper_bound_usd",
	"revenue.public_markets",
	"revenue.public_markets.fiscal_year_end",
	"revenue.public_markets.ipo_date",
	"revenue.public_markets.stock_symbols",
	"social_profiles",
	"social_profiles.crunchbase",
	"social_profiles.crunchbase.url",
	"social_profiles.crunchbase.uuid",
	"social_profiles.professional_network",
	"social_profiles.twitter_url",
	"software_reviews",
	"software_reviews.average_rating",
	"software_reviews.review_count",
	"software_reviews.review_count_mom_pct",
	"software_reviews.review_count_qoq_pct",
	"software_reviews.review_count_yoy_pct",
	"taxonomy",
	"taxonomy.categories",
	"taxonomy.professional_network_industry",
	"taxonomy.professional_network_specialities",
	"updated_at",
];

export const JOB_RETURN_PATHS: string[] = [
	"company",
	"company.basic_info",
	"company.basic_info.crustdata_company_id",
	"company.basic_info.industries",
	"company.basic_info.name",
	"company.basic_info.primary_domain",
	"company.basic_info.professional_network_id",
	"company.basic_info.website",
	"company.competitors",
	"company.competitors.websites",
	"company.followers",
	"company.followers.count",
	"company.funding",
	"company.funding.investors",
	"company.funding.last_fundraise_date",
	"company.funding.last_round_type",
	"company.funding.num_funding_rounds",
	"company.funding.total_investment_usd",
	"company.funding.valuation_usd",
	"company.headcount",
	"company.headcount.largest_headcount_country",
	"company.headcount.range",
	"company.headcount.total",
	"company.locations",
	"company.locations.city",
	"company.locations.country",
	"company.locations.state",
	"company.locations.street_address",
	"company.revenue",
	"company.revenue.acquisition_status",
	"company.revenue.estimated",
	"company.revenue.estimated.lower_bound_usd",
	"company.revenue.estimated.upper_bound_usd",
	"company.revenue.public_markets",
	"company.revenue.public_markets.fiscal_year_end",
	"company.revenue.public_markets.stock_symbols",
	"content",
	"content.description",
	"crustdata_job_id",
	"job_details",
	"job_details.category",
	"job_details.job_id",
	"job_details.number_of_openings",
	"job_details.reposted_job",
	"job_details.title",
	"job_details.url",
	"job_details.workplace_type",
	"location",
	"location.city",
	"location.country",
	"location.district",
	"location.pincode",
	"location.raw",
	"location.state",
	"metadata",
	"metadata.date_added",
	"metadata.date_updated",
];

export const SOCIALPOST_RETURN_PATHS: string[] = [
	"actor",
	"actor.actor_type",
	"actor.company_name",
	"actor.crustdata_entity_id",
	"actor.headline",
	"actor.industry",
	"actor.linkedin_id",
	"actor.location",
	"actor.location.city",
	"actor.location.continent",
	"actor.location.country",
	"actor.location.raw",
	"actor.location.state",
	"actor.name",
	"actor.professional_network_url",
	"actor.professional_network_urn",
	"actor.profile_picture_url",
	"actor.title",
	"article",
	"article.title",
	"article.url",
	"backend_urn",
	"comments",
	"comments.comment_reactions",
	"comments.comment_reactions.APPRECIATION",
	"comments.comment_reactions.EMPATHY",
	"comments.comment_reactions.ENTERTAINMENT",
	"comments.comment_reactions.INTEREST",
	"comments.comment_reactions.LIKE",
	"comments.comment_reactions.PRAISE",
	"comments.comment_text",
	"comments.comment_urn",
	"comments.commenter",
	"comments.commenter.actor_type",
	"comments.commenter.company",
	"comments.commenter.crustdata_entity_id",
	"comments.commenter.headline",
	"comments.commenter.industry",
	"comments.commenter.linkedin_id",
	"comments.commenter.location",
	"comments.commenter.name",
	"comments.commenter.professional_network_url",
	"comments.commenter.professional_network_urn",
	"comments.commenter.profile_picture_url",
	"comments.commenter.title",
	"comments.created_at",
	"comments.permalink",
	"content_types",
	"date_posted",
	"document",
	"document.page_count",
	"document.title",
	"document.url",
	"engagement",
	"engagement.num_shares",
	"engagement.reactions_by_type",
	"engagement.reactions_by_type.APPRECIATION",
	"engagement.reactions_by_type.EMPATHY",
	"engagement.reactions_by_type.ENTERTAINMENT",
	"engagement.reactions_by_type.INTEREST",
	"engagement.reactions_by_type.LIKE",
	"engagement.reactions_by_type.PRAISE",
	"engagement.total_comments",
	"engagement.total_reactions",
	"entity_urn",
	"has_video",
	"hashtags",
	"hyperlinks",
	"hyperlinks.company_professional_network_urls",
	"hyperlinks.media_urls",
	"hyperlinks.other_urls",
	"hyperlinks.person_professional_network_urls",
	"is_edited",
	"mentions",
	"mentions.company_ids",
	"mentions.person_ids",
	"metadata",
	"metadata.data_updated_at",
	"parent_post_urn",
	"poll",
	"poll.closed",
	"poll.multi_select",
	"poll.options",
	"poll.question",
	"poll.total_voters",
	"post_type",
	"reactors",
	"reactors.reaction_type",
	"reactors.reactor",
	"reactors.reactor.actor_type",
	"reactors.reactor.company",
	"reactors.reactor.crustdata_entity_id",
	"reactors.reactor.headline",
	"reactors.reactor.industry",
	"reactors.reactor.linkedin_id",
	"reactors.reactor.location",
	"reactors.reactor.name",
	"reactors.reactor.professional_network_url",
	"reactors.reactor.professional_network_urn",
	"reactors.reactor.profile_picture_url",
	"reactors.reactor.title",
	"reposter",
	"reposter.actor_type",
	"reposter.company_name",
	"reposter.crustdata_entity_id",
	"reposter.headline",
	"reposter.industry",
	"reposter.linkedin_id",
	"reposter.location",
	"reposter.location.city",
	"reposter.location.continent",
	"reposter.location.country",
	"reposter.location.raw",
	"reposter.location.state",
	"reposter.name",
	"reposter.professional_network_url",
	"reposter.professional_network_urn",
	"reposter.profile_picture_url",
	"reposter.title",
	"share_url",
	"share_urn",
	"text",
];

/** What each operation's `fields` parameter accepts, keyed `resource.operation`. */
export const FIELD_VOCABULARY: Record<string, string[]> = {
	"person.enrich": [
		"basic_profile",
		"professional_network",
		"skills",
		"social_handles",
		"experience",
		"education",
		"certifications",
		"honors",
		"dev_platform_profiles",
		"assessment",
		"social_posts",
	],
	"company.enrich": [
		"basic_info",
		"revenue",
		"headcount",
		"funding",
		"hiring",
		"web_traffic",
		"seo",
		"competitors",
		"employee_reviews",
		"people",
		"locations",
		"taxonomy",
		"followers",
		"news",
		"software_reviews",
		"social_profiles",
		"reviews",
		"public_launches",
		"market_intel",
		"metadata",
		"crustdata_company_id",
		"updated_at",
		"indexed_at",
		"social_posts",
	],
	"company.identify": [
		"crustdata_company_id",
		"basic_info",
		"social_profiles",
	],
	"person.contactEnrich": [
		"contact.business_emails",
		"contact.personal_emails",
		"contact.phone_numbers",
		"contact.websites",
	],
	"person.search": PERSON_RETURN_PATHS,
	"company.search": COMPANY_RETURN_PATHS,
	"job.search": JOB_RETURN_PATHS,
	"socialPost.search": SOCIALPOST_RETURN_PATHS,
};

/** Columns `aggregations` may group by. A strict subset of the filterable ones. */
export const JOB_AGGREGATION_FIELDS: string[] = [
	"company.basic_info.company_id",
	"company.basic_info.crustdata_company_id",
	"company.basic_info.industries",
	"company.basic_info.primary_domain",
	"company.funding.last_round_type",
	"company.headcount.range",
	"company.locations.country",
	"job_details.category",
	"job_details.title",
	"job_details.workplace_type",
	"location.country",
];

export const FILTER_OPERATORS: INodePropertyOptions[] = [
	{ name: "Equals", value: "eq" },
	{ name: "Not Equals", value: "ne" },
	{ name: "Less Than", value: "lt" },
	{ name: "Less than or Equal", value: "lte" },
	{ name: "Greater Than", value: "gt" },
	{ name: "Greater than or Equal", value: "gte" },
	{ name: "In (Value Is a List)", value: "in" },
	{ name: "Not in (Value Is a List)", value: "not_in" },
	{ name: "Contains All Words", value: "all_words" },
	{ name: "Does Not Contain", value: "not_contains" },
	{ name: "Exact Phrase", value: "exact_phrase" },
	{ name: "Has All (Nested Array)", value: "has_all" },
	{ name: "Within Distance", value: "geo_distance" },
	{ name: "Outside Distance", value: "geo_exclude" },
];

/** UI value -> the token the API expects. */
export const OPERATOR_TO_API: Record<string, string> = {
	"eq": "=",
	"ne": "!=",
	"lt": "<",
	"lte": "=<",
	"gt": ">",
	"gte": "=>",
	"in": "in",
	"not_in": "not_in",
	"all_words": "(.)",
	"not_contains": "(!)",
	"exact_phrase": "[.]",
	"has_all": "has_all",
	"geo_distance": "geo_distance",
	"geo_exclude": "geo_exclude",
};

/** Every synchronous endpoint, for the Raw operation. Batch and watch are excluded:
 *  each answers with a handle Raw has no way to redeem. */
export const SYNC_ENDPOINTS: Array<{ method: string; path: string }> = [
	{ method: "GET", path: "/account/credits" },
	{ method: "GET", path: "/account/endpoints" },
	{ method: "GET", path: "/account/usage/errors" },
	{ method: "GET", path: "/account/usage/events" },
	{ method: "GET", path: "/account/usage/summary" },
	{ method: "POST", path: "/company/enrich" },
	{ method: "POST", path: "/company/identify" },
	{ method: "POST", path: "/company/professional_network/search/live" },
	{ method: "POST", path: "/company/search" },
	{ method: "POST", path: "/company/search/autocomplete" },
	{ method: "POST", path: "/dev_platform/enrich" },
	{ method: "POST", path: "/employee_review/enrich" },
	{ method: "POST", path: "/job/professional_network/search/live" },
	{ method: "POST", path: "/job/search" },
	{ method: "POST", path: "/job/search/autocomplete" },
	{ method: "POST", path: "/person/contact/enrich" },
	{ method: "POST", path: "/person/enrich" },
	{ method: "POST", path: "/person/professional_network/enrich/live" },
	{ method: "POST", path: "/person/professional_network/search/live" },
	{ method: "POST", path: "/person/search" },
	{ method: "POST", path: "/person/search/autocomplete" },
	{ method: "POST", path: "/social_post/professional_network/enrich/live" },
	{ method: "POST", path: "/social_post/professional_network/search/live" },
	{ method: "POST", path: "/social_post/search" },
	{ method: "POST", path: "/web/enrich/live" },
	{ method: "POST", path: "/web/search/live" },
];

/** Batch submit endpoints. Each answers with a batch_id rather than records. */
export const BATCH_ENDPOINTS: Array<{ path: string; label: string; maxItems?: number }> = [
	{ path: "/batch/company/enrich", label: "company enrich", maxItems: 10000 },
	{ path: "/batch/company/professional_network/search/live", label: "company professional_network search live" },
	{ path: "/batch/company/search", label: "company search" },
	{ path: "/batch/job/search", label: "job search", maxItems: 10 },
	{ path: "/batch/person/contact/enrich", label: "person contact enrich", maxItems: 300 },
	{ path: "/batch/person/enrich", label: "person enrich", maxItems: 10000 },
	{ path: "/batch/person/identify", label: "person identify", maxItems: 300 },
	{ path: "/batch/person/professional_network/enrich/live", label: "person professional_network enrich live", maxItems: 300 },
	{ path: "/batch/person/professional_network/search/live", label: "person professional_network search live" },
	{ path: "/batch/person/search", label: "person search" },
	{ path: "/batch/person/verify", label: "person verify", maxItems: 10 },
	{ path: "/batch/social_post/professional_network/enrich/live", label: "social_post professional_network enrich live", maxItems: 10 },
];

/** The spec version these tables came from. The credential must send this exact value. */
export const SPEC_VERSION = "2025-11-01";

/** Spec-declared request properties per synchronous POST endpoint. Drift guard only. */
export const REQUEST_PARAMS: Record<string, readonly string[]> = {
	"/batch/company/enrich": ["chunk_size", "crustdata_company_ids", "domains", "fields", "names", "professional_network_profile_urls", "webhook_url"],
	"/batch/company/professional_network/search/live": ["fields", "filters", "max_results", "professional_network_search_url", "webhook_url"],
	"/batch/company/search": ["fields", "filters", "limit_per_page", "max_results", "sorts", "webhook_url"],
	"/batch/job/search": ["crustdata_company_ids", "fields", "webhook_url"],
	"/batch/person/contact/enrich": ["chunk_size", "fields", "professional_network_profile_urls", "verified", "webhook_url"],
	"/batch/person/enrich": ["business_emails", "chunk_size", "fields", "professional_network_profile_urls", "webhook_url"],
	"/batch/person/identify": ["business_emails", "emails", "professional_network_profile_urls", "webhook_url"],
	"/batch/person/professional_network/enrich/live": ["chunk_size", "fields", "professional_network_profile_urls", "webhook_url"],
	"/batch/person/professional_network/search/live": ["fields", "filters", "max_results", "professional_network_search_url", "webhook_url"],
	"/batch/person/search": ["fields", "filters", "limit_per_page", "max_results", "sorts", "webhook_url"],
	"/batch/person/verify": ["professional_network_profile_urls", "webhook_url"],
	"/batch/social_post/professional_network/enrich/live": ["chunk_size", "company_domains", "company_names", "company_professional_network_urls", "crustdata_company_ids", "limit", "max_comments", "max_reactors", "post_types", "professional_network_profile_urls", "social_post_urls", "webhook_url"],
	"/company/enrich": ["crustdata_company_ids", "domains", "exact_match", "fields", "names", "professional_network_profile_urls"],
	"/company/identify": ["crustdata_company_ids", "domains", "exact_match", "fields", "names", "professional_network_profile_urls"],
	"/company/professional_network/search/live": ["filters", "limit", "page", "professional_network_search_url"],
	"/company/search": ["cursor", "fields", "filters", "limit", "search", "sorts"],
	"/company/search/autocomplete": ["field", "limit", "query"],
	"/dev_platform/enrich": ["crustdata_person_id", "profile_url"],
	"/employee_review/enrich": ["crustdata_company_id"],
	"/job/professional_network/search/live": ["crustdata_company_id", "fields", "limit", "sorts"],
	"/job/search": ["aggregations", "cursor", "fields", "filters", "limit", "sorts"],
	"/job/search/autocomplete": ["field", "limit", "query"],
	"/person/contact/enrich": ["business_emails", "fields", "professional_network_profile_urls", "verified"],
	"/person/enrich": ["fields", "preview", "professional_network_profile_urls"],
	"/person/professional_network/enrich/live": ["fields", "professional_network_profile_urls"],
	"/person/professional_network/search/live": ["background_job", "filters", "job_id", "limit", "page", "post_processing", "preview", "professional_network_search_url"],
	"/person/search": ["count", "cursor", "explain", "fields", "filters", "limit", "post_processing", "preview", "return_query", "sorts"],
	"/person/search/autocomplete": ["field", "limit", "query"],
	"/social_post/professional_network/enrich/live": ["company_domain", "company_name", "company_professional_network_url", "crustdata_company_id", "fields", "limit", "max_comments", "max_reactors", "page", "post_types", "professional_network_profile_url", "social_post_url"],
	"/social_post/professional_network/search/live": ["content_type", "date_posted", "exact_keyword_match", "filters", "keyword", "limit", "page", "sort_by"],
	"/social_post/search": ["cursor", "fields", "filters", "limit", "sorts"],
	"/web/enrich/live": ["human_mode", "urls"],
	"/web/search/live": ["end_date", "human_mode", "location", "page", "query", "site", "sources", "start_date"],
};

/** Every `sources` value /web/search/live declares. The node offers a verified subset. */
export const WEB_SEARCH_SOURCES: readonly string[] = [
	"ai",
	"news",
	"scholar-articles",
	"scholar-articles-enriched",
	"scholar-author",
	"social",
	"web",
];

/** Every watch route in the spec. Drift guard only: /watch is excluded from Raw. */
export const WATCH_ROUTES: readonly string[] = [
	"DELETE /watch/{dataset}/search/{watch_id}",
	"DELETE /watch/{dataset}/{watch_id}",
	"DELETE /watch/{watch_id}",
	"GET /watch/{dataset}",
	"GET /watch/{dataset}/search",
	"GET /watch/{dataset}/search/{watch_id}",
	"GET /watch/{dataset}/{watch_id}",
	"GET /watch/{dataset}/{watch_id}/runs",
	"GET /watch/{dataset}/{watch_id}/runs/{run_id}/summary",
	"GET /watch/{watch_id}",
	"GET /watch/{watch_id}/runs",
	"GET /watch/{watch_id}/runs/{run_id}/summary",
	"PATCH /watch/{dataset}/search/{watch_id}",
	"PATCH /watch/{dataset}/{watch_id}",
	"PATCH /watch/{watch_id}",
	"POST /watch/{dataset}",
	"POST /watch/{dataset}/search",
	"POST /watch/{dataset}/search/{watch_id}/test",
	"POST /watch/{dataset}/test",
	"POST /watch/{dataset}/{watch_id}/test",
];

export const FILTER_COMBINATORS: INodePropertyOptions[] = [
	{ name: 'AND', value: 'and' },
	{ name: 'OR', value: 'or' },
	{ name: 'All of (Across Nested Array Elements)', value: 'all_of' },
];
